rocommunity public
agentaddress 127.0.0.1:1162
extend heartrate /opt/iot-sim/scripts/heartrate.sh
extend spo2 /opt/iot-sim/scripts/spo2.sh
extend battery /opt/iot-sim/scripts/battery.sh
sysname PatientMonitor2
